"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from core.secrets import secret_manager

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Sentinel so missing secrets fall back to the provided default instead of
# raising (``secret_manager.get_secret`` raises when no default is given).
_UNSET = object()


def _env_bool(name: str, default: bool = False) -> bool:
    """Read a boolean secret. Use ``True`` / ``False`` in ``.env`` (``1`` / ``0`` still work)."""
    value = secret_manager.get_secret(name, default=_UNSET)
    if value is _UNSET:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() not in {"0", "false", "no", "off"}


def _env_list(name: str, default: tuple[str, ...] = ()) -> list[str]:
    value = secret_manager.get_secret(name, default=_UNSET)
    if value is _UNSET or not value:
        return list(default)
    return [item.strip() for item in str(value).split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEBUG = _env_bool("DJANGO_DEBUG", default=True)

_secret_key = secret_manager.get_secret("DJANGO_SECRET_KEY", default=None)
if not _secret_key:
    if DEBUG:
        _secret_key = "django-insecure-!k+i%x8j^l)((y!n61e#sg%#u)9&m#ig&erejtc4y(yl(h+azl"
    else:
        raise ValueError(
            "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is disabled."
        )
SECRET_KEY = _secret_key

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", ("localhost", "127.0.0.1"))

CSRF_TRUSTED_ORIGINS = _env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    (
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
    ),
)

SERVE_MEDIA = _env_bool("SERVE_MEDIA", default=DEBUG)


# ---------------------------------------------------------------------------
# HTTPS / security headers
# ---------------------------------------------------------------------------
# When ``DEBUG`` is off we assume a TLS-terminating reverse proxy (Nginx,
# Caddy, ALB, Cloud Run, …) sits in front of uvicorn and forwards
# ``X-Forwarded-Proto: https``. That lets Django mark session/CSRF cookies
# as Secure and emit ``Cross-Origin-Opener-Policy: same-origin`` (browsers
# discard COOP on plain http:// origins, hence the
# "Cross-Origin-Opener-Policy header has been ignored" console warning).
#
# Override individual knobs via env vars when you intentionally run the
# production image over plain HTTP (e.g. smoke testing the container, or a
# private network with mTLS terminated elsewhere).
_behind_tls = _env_bool("DJANGO_BEHIND_TLS_PROXY", default=not DEBUG)

if _behind_tls:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", default=True)
    SECURE_HSTS_SECONDS = int(
        secret_manager.get_secret("DJANGO_SECURE_HSTS_SECONDS", default=31536000)
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
    )
    SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)
else:
    # Plain-HTTP deploy (or DEBUG). Strip COOP so the browser stops warning
    # in the console. Without TLS, COOP cannot be enforced anyway.
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "reflex_django",
    "dashboard",
    "core",
    "accounts",
    "analytics",
    "items",
    "chatbot",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "reflex_django.streaming_middleware.AsyncStreamingMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Defaults to SQLite (``DJANGO_DB_PATH`` overrides the file location) so local
# development needs zero setup. Set ``DJANGO_DB_ENGINE=postgresql`` plus the
# usual ``DJANGO_DB_NAME`` / ``DJANGO_DB_USER`` / ``DJANGO_DB_PASSWORD`` /
# ``DJANGO_DB_HOST`` / ``DJANGO_DB_PORT`` to use Postgres (see
# ``docker-compose.prod.yml``).

_db_engine = (
    str(secret_manager.get_secret("DJANGO_DB_ENGINE", default="") or "sqlite").lower()
)

if _db_engine in {"postgres", "postgresql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": str(secret_manager.get_secret("DJANGO_DB_NAME", default="rxdjango")),
            "USER": str(secret_manager.get_secret("DJANGO_DB_USER", default="rxdjango")),
            "PASSWORD": str(secret_manager.get_secret("DJANGO_DB_PASSWORD", default="")),
            "HOST": str(secret_manager.get_secret("DJANGO_DB_HOST", default="db")),
            "PORT": str(secret_manager.get_secret("DJANGO_DB_PORT", default="5432")),
            "CONN_MAX_AGE": int(
                secret_manager.get_secret("DJANGO_DB_CONN_MAX_AGE", default=600)
            ),
        }
    }
else:
    _db_path = secret_manager.get_secret("DJANGO_DB_PATH", default=None)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": Path(_db_path) if _db_path else BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

_site_origin = secret_manager.get_secret("REFLEX_DJANGO_SITE_ORIGIN", default=None)
if _site_origin:
    REFLEX_DJANGO_SITE_ORIGIN = _site_origin

AVATAR_MAX_BYTES = 2 * 1024 * 1024

REFLEX_DJANGO_AUTH = {
    "SIGNUP_ENABLED": True,
    "PASSWORD_RESET_ENABLED": True,
    "LOGIN_URL": "/login",
    "SIGNUP_URL": "/register",
    "LOGIN_REDIRECT_URL": "/",
    "LOGOUT_REDIRECT_URL": "/login",
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "noreply@localhost"

# REFLEX_DJANGO_CONTEXT_PROCESSORS = (
#     "reflex_django.reflex_context.builtin_user_context",
#     "reflex_django.reflex_context.builtin_i18n_context",
# )

# Vite 8.0.x (default in current reflex_base) ships Rolldown as its bundler;
# its CJS-interop layer emits ``var r=r(), t=t(), n=n(), i=i();`` inside
# memoized factory wrappers, which crashes ``recharts`` and the Reflex
# Socket.IO dispatcher at runtime with ``TypeError: <var> is not a function``.
# Pin the last Rollup-based Vite (7.3.3) until upstream ships a fix.
REFLEX_DJANGO_VITE_VERSION = "5.4.19"
