# Generated by Django 6.0.5 on 2026-05-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KpiSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("revenue", "Revenue"),
                            ("orders", "Orders"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("value", models.IntegerField()),
                ("previous_value", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "KPI snapshots",
            },
        ),
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("revenue", "Revenue"),
                            ("orders", "Orders"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.IntegerField()),
            ],
            options={
                "ordering": ("date",),
                "unique_together": {("metric_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="DeviceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.IntegerField()),
                (
                    "period",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=20,
                    ),
                ),
                ("fill", models.CharField(default="var(--gray-8)", max_length=50)),
            ],
            options={
                "unique_together": {("name", "period")},
            },
        ),
    ]
