# Generated by Django 6.0.5 on 2026-05-17 11:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=accounts.models.avatar_upload_to
            ),
        ),
    ]
