"""ChatGPT-style chat UI for the chatbot page (ReflexGPT layout)."""

import reflex as rx
from reflex.constants.colors import ColorType

from chatbot.state import QA, ChatbotState


def message_content(text: str, color: ColorType) -> rx.Component:
    """Create a message content component.

    Args:
        text: The text to display.
        color: The color of the message.

    Returns:
        A component displaying the message.
    """
    return rx.markdown(
        text,
        background_color=rx.color(color, 4),
        color=rx.color(color, 12),
        display="inline-block",
        padding_inline="1em",
        border_radius="8px",
    )


def message(qa: QA) -> rx.Component:
    """A single question/answer message.

    Args:
        qa: The question/answer pair.

    Returns:
        A component displaying the question/answer pair.
    """
    return rx.box(
        rx.box(
            message_content(qa["question"], "mauve"),
            text_align="right",
            margin_bottom="8px",
        ),
        rx.box(
            message_content(qa["answer"], "accent"),
            text_align="left",
            margin_bottom="8px",
        ),
        max_width="50em",
        margin_inline="auto",
        width="100%",
    )


def chat() -> rx.Component:
    """List all the messages in a single conversation."""
    return rx.auto_scroll(
        rx.foreach(ChatbotState.selected_chat, message),
        flex="1",
        width="100%",
        padding="8px",
    )


def sessions_bar() -> rx.Component:
    """Top action bar: start, switch, or delete chat sessions."""
    return rx.hstack(
        rx.button(
            rx.icon("plus", size=16),
            "New chat",
            on_click=ChatbotState.new_chat,
            variant="soft",
        ),
        rx.spacer(),
        rx.menu.root(
            rx.menu.trigger(
                rx.button(
                    rx.icon("history", size=16),
                    "Sessions",
                    variant="soft",
                    color_scheme="gray",
                ),
            ),
            rx.menu.content(
                rx.cond(
                    ChatbotState.sessions.length() > 0,
                    rx.foreach(
                        ChatbotState.sessions,
                        lambda s: rx.menu.item(
                            s["title"],
                            on_click=ChatbotState.select_chat(s["id"]),
                        ),
                    ),
                    rx.menu.item("No sessions yet", disabled=True),
                ),
            ),
        ),
        rx.button(
            rx.icon("trash-2", size=16),
            on_click=ChatbotState.delete_chat,
            variant="soft",
            color_scheme="red",
            disabled=ChatbotState.current_session_id < 0,
            title="Delete current chat",
        ),
        width="100%",
        max_width="50em",
        margin_inline="auto",
        align="center",
    )


def action_bar() -> rx.Component:
    """The action bar to send a new message."""
    return rx.center(
        rx.vstack(
            rx.form(
                rx.hstack(
                    rx.input(
                        rx.input.slot(
                            rx.tooltip(
                                rx.icon("info", size=18),
                                content="Enter a question to get a response.",
                            )
                        ),
                        placeholder="Type something...",
                        id="question",
                        flex="1",
                    ),
                    rx.button(
                        "Send",
                        loading=ChatbotState.processing,
                        disabled=ChatbotState.processing,
                        type="submit",
                    ),
                    max_width="50em",
                    margin="0 auto",
                    align_items="center",
                    width="100%",
                ),
                reset_on_submit=True,
                on_submit=ChatbotState.process_question,
                width="100%",
            ),
            rx.text(
                "Responses are generated by OpenAI and may be factually incorrect or "
                "misleading. Use discretion.",
                text_align="center",
                font_size=".75em",
                color=rx.color("mauve", 10),
            ),
           
        ),
        position="sticky",
        bottom="0",
        left="0",
        padding_y="16px",
        backdrop_filter="auto",
        backdrop_blur="lg",
        border_top=f"1px solid {rx.color('mauve', 3)}",
        background_color=rx.color("mauve", 2),
        align="stretch",
        width="100%",
    )
